import { StyleSheet } from "react-native";

import { colors, radius, spacing } from "@/theme";

export const styles = StyleSheet.create({
  keyboardContainer: { flex: 1 },
  header: { backgroundColor: colors.accent, minHeight: 260, overflow: "hidden", position: "relative" },
  headerSearchActive: { minHeight: 106 },
  headerImage: { bottom: 77, height: 175, position: "absolute", right: -20, width: 267, zIndex: 1 },
  headerContent: { maxWidth: "64%", paddingHorizontal: spacing.xl, paddingTop: spacing.xl, zIndex: 1 },
  headerTitle: { fontSize: 30, fontWeight: "700" },
  headerSubtitle: { lineHeight: 22, marginTop: spacing.sm },
  headerSummary: { alignItems: "center", alignSelf: "flex-start", flexDirection: "row", marginTop: spacing.md },
  pendingDot: { backgroundColor: colors.primary, borderRadius: radius.full, height: 9, marginRight: spacing.sm, width: 9 },
  headerSummaryText: { fontSize: 13, fontWeight: "600" },
  searchBar: { alignItems: "center", backgroundColor: colors.white, borderRadius: radius.md, bottom: spacing.xl + spacing.xs, flexDirection: "row", left: spacing.xl, minHeight: 52, paddingHorizontal: spacing.md, position: "absolute", right: spacing.xl, zIndex: 2 },
  searchBarFocused: { bottom: spacing.lg },
  searchInput: { color: colors.text, flex: 1, fontSize: 15, marginLeft: spacing.sm, paddingVertical: 0 },
  taskList: { flex: 1 },
  content: { flexGrow: 1, paddingBottom: spacing.xl, paddingHorizontal: spacing.xl, paddingTop: spacing.xl },
  listHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  listHeaderActions: { alignItems: "center", flexDirection: "row", gap: spacing.sm },
  createTaskButton: { backgroundColor: colors.primary, borderRadius: radius.full, minWidth: 94, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm },
  createTaskButtonText: { fontSize: 12, fontWeight: "700" },
  modalOverlay: { backgroundColor: "rgba(15, 23, 42, 0.4)", flex: 1 },
  modalBackdrop: { bottom: 0, left: 0, position: "absolute", right: 0, top: 0 },
  modalKeyboardContainer: { flex: 1, justifyContent: "flex-end" },
  taskMenuSheet: { backgroundColor: colors.white, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, marginTop: "auto", paddingBottom: spacing.xxl, paddingHorizontal: spacing.xl },
  taskMenuTitle: { marginTop: spacing.lg },
  taskMenuSubtitle: { marginTop: spacing.xs },
  taskMenuOption: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: spacing.lg, minHeight: 44 },
  taskMenuDangerOption: { borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth, marginTop: spacing.sm, paddingTop: spacing.sm },
  taskMenuOptionText: { fontSize: 15, fontWeight: "400" },
  createTaskSheet: { backgroundColor: colors.white, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, flexShrink: 1, maxHeight: "88%", paddingBottom: spacing.xl, paddingHorizontal: spacing.xl },
  sheetHandleTouchArea: { alignSelf: "center", paddingHorizontal: spacing.xl, paddingVertical: spacing.sm },
  sheetHandle: { alignSelf: "center", backgroundColor: colors.border, borderRadius: radius.full, height: 4, marginTop: spacing.sm, width: 42 },
  sheetHeader: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between", marginTop: spacing.lg },
  sheetSubtitle: { marginTop: 3 },
  closeSheetButton: { alignItems: "center", backgroundColor: colors.surfaceSecondary, borderRadius: radius.full, height: 34, justifyContent: "center", width: 34 },
  closeSheetButtonText: { fontSize: 25, fontWeight: "300", lineHeight: 28 },
  createFormScroll: { flexShrink: 1 },
  createForm: { gap: spacing.lg, paddingBottom: spacing.md, paddingTop: spacing.xl },
  inputLabel: { fontSize: 13, fontWeight: "600", marginBottom: spacing.xs },
  formInput: { backgroundColor: colors.surfaceSecondary, borderColor: "transparent", borderRadius: radius.md, borderWidth: 1, color: colors.text, fontSize: 15, minHeight: 48, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  formInputError: { borderColor: colors.danger },
  formFieldError: { marginTop: spacing.xs },
  descriptionInput: { minHeight: 88 },
  readOnlyFormField: { backgroundColor: colors.surfaceSecondary, borderRadius: radius.md, justifyContent: "center", minHeight: 48, paddingHorizontal: spacing.md },
  dateTimePickerRow: { flexDirection: "row", gap: spacing.sm },
  formDatePicker: { alignItems: "center", backgroundColor: colors.surfaceSecondary, borderRadius: radius.md, flex: 1, flexDirection: "row", minHeight: 58, paddingHorizontal: spacing.sm },
  formDatePickerDisabled: { opacity: 0.52 },
  dateTimePickerCopy: { flex: 1, marginLeft: spacing.xs },
  dateTimePickerLabel: { fontSize: 10, fontWeight: "600" },
  dateTimePickerValue: { fontSize: 15, fontWeight: "400", marginTop: 2 },
  priorityOptions: { flexDirection: "row", gap: spacing.xs },
  priorityOption: { alignItems: "center", borderColor: colors.border, borderRadius: radius.full, borderWidth: 1, flex: 1, minHeight: 48, justifyContent: "center", paddingHorizontal: 2 },
  priorityOptionText: { fontSize: 11, fontWeight: "700" },
  sheetActions: { flexDirection: "row", gap: spacing.md },
  cancelCreateButton: { alignItems: "center", backgroundColor: colors.surfaceSecondary, borderRadius: radius.md, flex: 1, justifyContent: "center", minHeight: 52 },
  cancelCreateButtonText: { fontSize: 14, fontWeight: "700" },
  saveCreateButton: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.md, flex: 1.4, justifyContent: "center", minHeight: 52 },
  saveCreateButtonPressed: { opacity: 0.8 },
  saveCreateButtonText: { fontSize: 14, fontWeight: "700" },
  classroomSyncRow: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: spacing.lg, minHeight: 64, paddingHorizontal: spacing.md },
  classroomSyncInfo: { alignItems: "center", flexDirection: "row", gap: spacing.sm },
  classroomSyncTitle: { fontSize: 14, fontWeight: "600" },
  classroomSyncActionGroup: { alignItems: "center", gap: 2 },
  classroomSyncAction: { fontSize: 13, fontWeight: "700" },
  classroomSyncRowLoading: { justifyContent: "center" },
  classroomSyncRowPressed: { backgroundColor: colors.surfaceSecondary },
  taskSection: { backgroundColor: colors.white, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, marginTop: spacing.xl, overflow: "hidden" },
  sectionHeader: { alignItems: "center", borderBottomLeftRadius: 0, borderBottomRightRadius: 0, borderTopLeftRadius: radius.md, borderTopRightRadius: radius.md, flexDirection: "row", justifyContent: "space-between", marginBottom: 0, paddingHorizontal: spacing.lg, paddingVertical: spacing.md },
  sectionHeaderRight: { alignItems: "center", flexDirection: "row", gap: spacing.sm },
  sectionHeaderCollapsed: { borderBottomLeftRadius: radius.md, borderBottomRightRadius: radius.md },
  sectionHeaderPressed: { opacity: 0.8 },
  sectionCount: { alignItems: "center", backgroundColor: "rgba(255, 255, 255, 0.24)", borderRadius: radius.full, minWidth: 24, paddingHorizontal: spacing.sm, paddingVertical: 3 },
  sectionCountText: { fontSize: 11, fontWeight: "700" },
  sectionTaskTotal: { fontSize: 14, fontWeight: "400" },
  sectionEmpty: { minHeight: 74, justifyContent: "center", paddingHorizontal: spacing.lg },
  sectionEmptyText: { textAlign: "center" },
  taskCard: { backgroundColor: colors.white, borderRadius: 0, borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth, borderWidth: 0, marginTop: 0, padding: spacing.lg },
  taskTopRow: { alignItems: "flex-start", flexDirection: "row" },
  taskActions: { alignItems: "center", marginLeft: spacing.md, minWidth: 106, paddingLeft: spacing.md },
  taskCheckbox: { alignItems: "center", height: 27, justifyContent: "center", marginTop: spacing.sm, width: 27 },
  taskTitleContainer: { flex: 1 },
  taskTitle: { fontSize: 17, fontWeight: "600", lineHeight: 22 },
  priorityPill: { backgroundColor: "rgba(255, 255, 255, 0.66)", borderRadius: radius.full, marginTop: spacing.xs, paddingHorizontal: spacing.sm, paddingVertical: 5 },
  priorityText: { fontSize: 11, fontWeight: "700" },
  courseName: { marginBottom: spacing.xs },
  taskSourceRow: { alignItems: "center", alignSelf: "flex-end", flexDirection: "row", gap: spacing.xs },
  sourceBadge: { borderRadius: radius.full, paddingHorizontal: spacing.md, paddingVertical: spacing.xs },
  sourceBadgeText: { fontSize: 11, fontWeight: "700" },
  taskMenuTrigger: { alignItems: "center", height: 28, justifyContent: "center", width: 22 },
  taskFooter: { alignItems: "center", backgroundColor: colors.surface, borderRadius: radius.sm, flexDirection: "row", justifyContent: "space-between", marginTop: spacing.md, paddingHorizontal: spacing.sm, paddingVertical: spacing.sm },
  dueDetails: { alignItems: "flex-end" },
  dueDate: { fontWeight: "700" },
  dueTime: { marginTop: 2 },
  instructionsPreview: { marginTop: spacing.xs },
  instructionsText: { lineHeight: 19 },
  instructionsPreviewLabel: { fontWeight: "600", marginTop: spacing.xs },
});
