import { StyleSheet } from "react-native";

import { colors, radius, spacing } from "@/theme";

export const styles = StyleSheet.create({
  header: {
    backgroundColor: colors.primary,
    minHeight: 240,
    overflow: "hidden",
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xxl
  },
  headerImage: { height: 200, position: "absolute", right: -68, top: -10, width: 260, zIndex: 1 },
  headerCopy: { marginTop: -spacing.sm, maxWidth: "58%", zIndex: 2 },
  headerDescription: { fontSize: 15, lineHeight: 20, marginTop: 3 },
  headerHint: { fontSize: 12, fontWeight: "600", lineHeight: 17, marginTop: spacing.sm, opacity: 0.82 },
  aiButton: {
    alignItems: "center",
    alignSelf: "stretch",
    backgroundColor: colors.white,
    borderRadius: radius.lg,
    flexDirection: "row",
    marginTop: spacing.md,
    minHeight: 50,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    zIndex: 2,
  },
  aiBadge: {
    alignItems: "center",
    height: 34,
    justifyContent: "center",
    marginLeft: spacing.xs,
    marginRight: spacing.sm,
    position: "relative",
    width: 31,

  },
  aiBadgeMain: { fontSize: 24, fontWeight: "700", lineHeight: 27 },
  aiBadgeSmall: { fontSize: 12, fontWeight: "700", left: 0, position: "absolute", top: 1 },
  aiButtonCopy: { flex: 1 },
  aiButtonTitle: { fontSize: 15, fontWeight: "700" },
  aiButtonCaption: { marginTop: 2 },
  aiButtonPressed: { opacity: 0.82 },
  aiLoading: { marginLeft: spacing.md },
  aiPlanReadyTitle: { fontSize: 16, fontWeight: "800" },
  aiPlanReadyMeta: { fontSize: 11, marginTop: 3 },
  aiRefreshAction: { alignItems: "center", justifyContent: "center", marginLeft: spacing.sm, minWidth: 48 },
  aiRefreshActionText: { fontSize: 10, fontWeight: "800", marginTop: 1 },
  viewTabs: { backgroundColor: colors.white, flexDirection: "row", overflow: "hidden" },
  viewTab: { alignItems: "center", borderBottomColor: "transparent", borderBottomWidth: 3, flex: 1, minHeight: 43, justifyContent: "center", paddingHorizontal: spacing.xs },
  viewTabActive: { borderBottomColor: colors.primary },
  viewTabText: { fontSize: 14, fontWeight: "700" },
  loading: { alignItems: "center", flex: 1, justifyContent: "center" },
  aiContent: { gap: spacing.md, paddingHorizontal: spacing.xl, paddingTop: spacing.xxl + spacing.sm, paddingBottom: spacing.xl },
  aiEmptyState: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, marginTop: spacing.lg, paddingHorizontal: spacing.xl, paddingVertical: spacing.xxl },
  aiEmptyTitle: { fontSize: 17, fontWeight: "700", textAlign: "center" },
  aiEmptyText: { lineHeight: 21, marginTop: spacing.sm, textAlign: "center" },
  aiSectionIntro: { marginBottom: spacing.sm },
  aiSectionDescription: { lineHeight: 21, marginTop: spacing.xs },
  criticalJourney: { marginTop: spacing.sm },
  criticalJourneyBanner: { backgroundColor: colors.primary, borderRadius: radius.lg, paddingHorizontal: spacing.lg, paddingVertical: spacing.lg },
  criticalJourneyBannerEyebrow: { fontSize: 10, fontWeight: "800", letterSpacing: 0.7, opacity: 0.84 },
  criticalJourneyBannerTitle: { fontSize: 24, fontWeight: "800", marginTop: 4 },
  criticalJourneyBannerCaption: { marginTop: 4, opacity: 0.9 },
  criticalJourneyDivider: { alignItems: "center", flexDirection: "row", gap: spacing.md, marginTop: spacing.xl },
  criticalJourneyDividerLine: { backgroundColor: colors.border, flex: 1, height: StyleSheet.hairlineWidth },
  criticalJourneyDividerText: { fontSize: 13, fontWeight: "700" },
  criticalJourneyMap: { marginTop: spacing.xl, overflow: "hidden", position: "relative" },
  criticalJourneyRoute: { left: 0, position: "absolute", top: 0 },
  criticalJourneyStep: { alignItems: "center", position: "absolute", width: "32%" },
  criticalJourneyNode: { alignItems: "center", backgroundColor: colors.primary, borderColor: "#1687DB", borderRadius: radius.full, borderWidth: 1, elevation: 6, height: 62, justifyContent: "center", shadowColor: "#1687DB", shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.42, shadowRadius: 0, width: 62 },
  criticalJourneyNodeCurrent: { backgroundColor: colors.accent, borderColor: "#E4B900", shadowColor: "#E4B900" },
  criticalJourneyTaskTitle: { fontSize: 12, fontWeight: "700", lineHeight: 16, marginTop: spacing.sm, textAlign: "center" },
  criticalJourneyMeta: { alignItems: "center", flexDirection: "row", marginTop: 3 },
  criticalJourneyFinish: { alignItems: "center", flexDirection: "row", gap: spacing.sm, justifyContent: "center", marginTop: -spacing.sm },
  criticalJourneyFinishMark: { backgroundColor: colors.success, borderColor: colors.white, borderRadius: radius.full, borderWidth: 3, height: 20, width: 20 },
  criticalRoute: { paddingBottom: spacing.sm, position: "relative" },
  criticalRouteLine: { backgroundColor: "#C7E7FC", bottom: 32, left: 18, position: "absolute", top: 19, width: 2 },
  criticalRouteStep: { alignItems: "flex-start", flexDirection: "row", paddingBottom: spacing.md, position: "relative" },
  criticalRouteOrder: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.full, height: 38, justifyContent: "center", width: 38, zIndex: 1 },
  criticalRouteOrderText: { fontSize: 14, fontWeight: "800" },
  criticalRouteCard: { backgroundColor: colors.white, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flex: 1, marginLeft: spacing.md, padding: 0 },
  criticalRouteCardBody: { padding: spacing.lg },
  criticalRouteTitleRow: { alignItems: "flex-start", flexDirection: "row", gap: spacing.sm },
  criticalRouteTitleCopy: { flex: 1 },
  criticalRouteTitle: { fontSize: 16, fontWeight: "700", lineHeight: 21 },
  criticalRouteRiskRow: { alignItems: "center", flexDirection: "row", gap: 5, marginTop: 5 },
  criticalRouteRiskDot: { borderRadius: radius.full, height: 8, width: 8 },
  criticalRouteRiskText: { fontSize: 10, fontWeight: "800" },
  criticalRouteMeta: { borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth, lineHeight: 18, marginTop: spacing.xs, paddingBottom: spacing.xs },
  criticalRouteDescription: { lineHeight: 18, marginTop: spacing.sm },
  criticalTable: { backgroundColor: colors.white, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, overflow: "hidden", padding: 0 },
  criticalTableHeader: { alignItems: "center", backgroundColor: colors.surfaceSecondary, flexDirection: "row", minHeight: 42, paddingHorizontal: spacing.sm },
  criticalTableRow: { alignItems: "center", borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", minHeight: 61, paddingHorizontal: spacing.sm },
  criticalOrderColumn: { width: 30 },
  criticalNameColumn: { flex: 1, fontSize: 13, fontWeight: "600", paddingHorizontal: spacing.xs },
  criticalRiskColumn: { alignItems: "center", width: 72 },
  criticalMinutesColumn: { fontSize: 13, textAlign: "right", width: 42 },
  criticalTaskOrder: { alignItems: "center", backgroundColor: "#EAF3FF", borderRadius: radius.full, height: 26, justifyContent: "center", width: 26 },
  criticalTaskOrderText: { fontSize: 12, fontWeight: "700" },
  riskPill: { alignItems: "center", backgroundColor: "#FFF0F0", borderRadius: radius.full, minWidth: 58, paddingHorizontal: spacing.xs, paddingVertical: 4 },
  riskPillText: { fontWeight: "700" },
  planStats: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flexDirection: "row", justifyContent: "space-around", paddingVertical: spacing.md },
  planStat: { alignItems: "center", flex: 1 },
  planStatValue: { fontSize: 22, fontWeight: "700" },
  planStatDivider: { backgroundColor: colors.border, height: 33, width: StyleSheet.hairlineWidth },
  planDateTabs: { gap: spacing.sm, paddingVertical: spacing.xs },
  planDateTab: { alignItems: "center", backgroundColor: colors.white, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, minWidth: 58, paddingHorizontal: spacing.sm, paddingVertical: spacing.sm },
  planDateTabActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  planDateWeekday: { fontWeight: "700", textTransform: "capitalize" },
  planDateNumber: { fontSize: 17, fontWeight: "700", marginTop: 1 },
  planBlockCard: { backgroundColor: colors.white, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, padding: spacing.lg },
  planBlockDate: { fontWeight: "700", textTransform: "capitalize" },
  planBlockRow: { flexDirection: "row", marginTop: spacing.sm },
  planBlockTime: { borderRightColor: colors.border, borderRightWidth: StyleSheet.hairlineWidth, minWidth: 62, paddingRight: spacing.sm },
  planBlockTimeText: { fontSize: 16, fontWeight: "700" },
  planBlockCopy: { flex: 1, paddingLeft: spacing.md },
  planBlockTitle: { fontSize: 16, fontWeight: "700", lineHeight: 21 },
  planBlockReason: { lineHeight: 18, marginTop: 3 },
  planWarning: { backgroundColor: "#FFF8E7", borderRadius: radius.sm, padding: spacing.md },
  columnsContent: { gap: spacing.md, paddingHorizontal: spacing.xl, paddingVertical: spacing.xl },
  column: {
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    height: "100%",
    overflow: "hidden",
  },
  columnHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  columnCount: { backgroundColor: "rgba(255, 255, 255, 0.25)", borderRadius: radius.full, minWidth: 25, paddingHorizontal: spacing.sm, paddingVertical: 3 },
  columnCountText: { fontSize: 12, fontWeight: "700", textAlign: "center" },
  columnList: { gap: spacing.sm, padding: spacing.sm },
  emptyColumn: { alignItems: "center", minHeight: 130, justifyContent: "center", paddingHorizontal: spacing.xl },
  emptyColumnText: { lineHeight: 21, textAlign: "center" },
  taskCard: { backgroundColor: colors.white, borderRadius: radius.sm, padding: spacing.lg },
  courseName: { marginBottom: spacing.xs },
  taskTitle: { fontSize: 17, fontWeight: "600", lineHeight: 22 },
  description: { lineHeight: 19, marginTop: spacing.sm },
  aiTaskMeta: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs, marginTop: spacing.sm },
  aiTaskMetaText: { fontWeight: "700" },
  taskMeta: { alignItems: "center", borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", justifyContent: "space-between", marginTop: spacing.md, paddingTop: spacing.md },
  moveButton: { backgroundColor: colors.surfaceSecondary, borderRadius: radius.full, paddingHorizontal: spacing.sm, paddingVertical: 5 },
  moveButtonText: { fontWeight: "700" },
  moveButtonPressed: { opacity: 0.72 },
});
